---
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: library
data:
  APP_NAME: "Book Service"
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  ALGORITHM: "HS256"
  USER_SERVICE_URL: "http://user-service:8000"
