---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-service-config
  namespace: library
data:
  APP_NAME: "Loan Service"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  ALGORITHM: "HS256"
  USER_SERVICE_URL: "http://user-service:8000"
  BOOK_SERVICE_URL: "http://book-service:8001"
