---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: library
  labels:
    app: loan-service
spec:
  type: ClusterIP
  selector:
    app: loan-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
